# Generated by Django 2.1.2 on 2018-10-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='linkname',
            field=models.CharField(blank=True, max_length=64, verbose_name='ссылка'),
        ),
    ]
