# Generated by Django 2.1.2 on 2018-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_productcategory_linkname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='linkname',
            field=models.CharField(default='#', max_length=64, verbose_name='ссылка'),
        ),
    ]
