# Generated by Django 2.1.2 on 2018-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20181029_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='linkname',
            field=models.CharField(blank=True, max_length=64, verbose_name='ссылка'),
        ),
    ]
