# Generated by Django 2.1.2 on 2018-10-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20181029_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='linkname',
        ),
    ]
