# Generated by Django 2.1.2 on 2018-10-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_productcategory_linkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='linkname',
            field=models.CharField(blank=True, max_length=64, verbose_name='ссылка'),
        ),
    ]
