# Generated by Django 2.1.2 on 2018-10-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_productcategory_pathname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='linkname',
        ),
    ]
